name: Analyze, Build and Deploy
on: [push]
jobs:
  analyze:
    name: "Analyze"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ğŸ¦ Setup Flutter
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: latest
      - name: ğŸ“¦ Install Dependencies
        run: flutter pub get
      - name: 'Analyzing'
        run: dart analyze

  build:
    name: Build
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ğŸ¦ Setup Flutter
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: latest
      - name: ğŸ“¦ Install Dependencies
        run: flutter pub get
      - name: ğŸ› ï¸ Build the web application
        run: flutter build web -t lib/main.dart
      - name: ğŸ› ï¸ Build the android application
        run: flutter build apk --split-per-abi
      - name: â¬‡ï¸ Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build/web